name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: make
